services:
  notebook:
    image: node:24
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm i -g pnpm && bash startup.sh"
    ports:
      - "8708:8080"
    env_file:
      - .env
